import {
  AlertTriangle,
  Activity,
  CheckCircle2,
  Clock,
  CornerUpLeft,
  Eye,
  FileText,
  Filter,
  Hand,
  Headphones,
  Inbox,
  LoaderCircle,
  Lock,
  MessageSquare,
  RefreshCw,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  ThumbsUp,
  UserCheck,
  Users,
  XCircle,
  type LucideIcon,
} from 'lucide-react'
import type { SupportThreadStatus } from '@/lib/supportChatService'

/** Central icon registry for the Operator & Compliance Portal. */
export const OPERATOR_ICONS = {
  tab: {
    support: Headphones,
    reports: ShieldAlert,
    logs: Activity,
    messages: MessageSquare,
    rbac: Lock,
  },
  stat: {
    reports: ShieldAlert,
    logs: Activity,
    operators: Users,
    support: Headphones,
  },
  status: {
    OPEN: Clock,
    IN_PROGRESS: LoaderCircle,
    RESOLVED: CheckCircle2,
  } satisfies Record<SupportThreadStatus, LucideIcon>,
  sender: {
    user: Inbox,
    operator: CornerUpLeft,
    system: Sparkles,
  },
  quickReply: {
    greeting: Hand,
    escrow: ShieldCheck,
    resolved: ThumbsUp,
  },
  ui: {
    search: Search,
    refresh: RefreshCw,
    eye: Eye,
    fileText: FileText,
    xCircle: XCircle,
    clock: Clock,
    checkCircle: CheckCircle2,
    shieldAlert: ShieldAlert,
    lock: Lock,
    userCheck: UserCheck,
    filter: Filter,
    send: Send,
    sparkles: Sparkles,
    alertTriangle: AlertTriangle,
    message: MessageSquare,
  },
} as const
